language: elixir
sudo: required
cache:
  directories:
    - deps
services:
  - docker
  - postgresql
addons:
  postgresql: "9.5"
elixir:
  - 1.4.4
otp_release:
  - 20.0
env:
  global:
    - MIX_ENV=test
    - DOCKER_HUB_ACCOUNT=nebo15
    - MAIN_BRANCHES="master develop staging" # Branches on which you want version to be incremented
    - RELEASE_BRANCH="master"
    # Docker and GitHub credentials
    - secure: "L4yAydvmMfmW96p8Blr0Ke9q8Cj3x6dDZ3Yuw+v4MREZNRLD3pmlMxqddDdjPp7WGd3gbGKeDudh5czfkWSaCfclI689l/PYAukqMSjKcmPneZFZGAnbQPZoJSYn7VeNZNXhv0Fq2uplnji1Qek3aHCXXf3LlIrmSU4MBZeNnJgZMqWDGZNOJR0N/lAWC277dRL3RiDBSPrYjH/N73B1JSkX89tRT3pH0SFxkfLCeCbCI9y/UHp7FAtgHsNkpEu059iz/CoKOry7Yr0w8zmBTMwQiqz/ZSZN06qeiRv6EKHejLFXxuEGEIEouQQu+NlwrIgBnlQwqA4OJDuAuKJCGt8etytYTc59l2zfwh2Smo9ck20sHS+RxfNY/TNlowyEc55MOcw+wy00rDGT/JbhjFD56zFopgSOWa6Io28F4WCBYhM8UPih8B1zp6ZBeQC4jofK7/abp6AZIpI822AF68R2YyA1uLKPVKVKSJyWux71uKDyksgEYd3nxQ2QS/FZjOTY5CeLMU/Q0nrQcf+yFa4gHzwM+aG+wglV0yhIP+QIRh9hmrCUSXIvqLZhx0L01nngoXfl8LeXw2MrOCzLuswXsDwiv7DWFgoyZgzkWjfvXe6qcamKDu0a5N16sLUnH7bkjveO35i0dA+BHoP73qX/b/cJHPnWmeF9gyaNwNo="
    - secure: "Eo4EaR6TKJ6PImEIg2dfkNFsTPFqYH4TknpcnH64cg9Z0JjPfkAQsAOdwJ/RkkoCKa5UyW5D1fqOxWRT9DsFhUwQRsNXA26Tstu60Uz4RFcmHFicuZoHLOBadFzm+VpZ0Y+Ycz0jweophGqyldMShvox1GcpCkOz/4tyxU2W7P9Ty+rHta4oFIKYBRe4tBc20+jdY1yc/F5VWcN1qhE686cIwxyxaHx79RxgqBI0mM2RyPdTcmqBz8ceyUJ8RAUZArzjy/s79x6jNU+lTZDmxFsU4bHRp/ORIOtTuZkJcK2u7O2dlH1lsug2N9aXgg5Osw5b8XeA31bJucjgiwIdSeCPrXdhIJKdmDD5bT62XuUh6z9KfRSe00XKAqwf6hH3/AaivVdSSuenlnwGSh3OaMDJqZNPoauEl4W2FnJO/UBEFbIbuBA509Ccep3stKKoEzvT97+e5dJoMa99nHZBkVt9S3h92HQwcAbQdpQUUupMUnkUnU7+Q80h+9y4Ncri7Ps0MdBpne00Fpu7618L9lSOxbRCh+hDiSXlT9gclgPB0htehNByDIaQVUpaG3cYIc15CrPPjuoT5P1cpG8HBLZfZTFsMPdhH7zB7xzwfqQsPJUqoDcm7k5V2G35j7KjLasBAqlFONjrqmB4C82DIA2stTmw2/eZHDgEBl28mOM="
branches:
  # Releases are generated automatically, stop infinite build loop
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  # Expose MQ and DB to Docker container
  - sudo ./bin/ci/init-db.sh
script:
  # Increment version in mix.exs
  - ./bin/ci/version-increment.sh
  # Install dependencies
  - mix deps.get
  # Run all tests except pending ones
  - mix test --exclude pending --trace
  # Submit code coverage report to Coveralls
  # Add --pro if you using private repo.
  - mix coveralls.travis --exclude pending
  # Run static code analysis
  - mix credo --strict
  # Check code style
  - mix dogma
  # Build Docker container
  - ./bin/build.sh
  # Initialize DB for Docker container
  - MIX_ENV=dev mix ecto.setup
  # Run Docker container
  - sudo ./bin/start.sh
  - sleep 5
  - docker ps
  - RUNNING_CONTAINERS=`docker ps | wc -l`;
    if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "1" ]; then
      echo "[E] Container is not started\!";
      docker logs otp_verification_api --details --since 5h;
      exit 1;
    fi;
  # Run acceptance tests on Docker container
  - "CONTAINER_HTTP_HOST=localhost CONTAINER_HTTP_PORT=4000 mix test test/acceptance"
after_failure:
  - docker logs otp_verification_api --details --since 5h
after_success:
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/push.sh
